x-logging-config: &logging-config
  driver: "json-file"
  options:
    max-size: "2g"
    max-file: "2"

services:

  postgres_rome:
    container_name: postgres_rome
    image: postgres:15
    logging: *logging-config
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: test_rollup
      POSTGRES_USER: hercules
      POSTGRES_PASSWORD: qwerty123
    hostname: postgres_rome
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ CMD-SHELL, "pg_isready -h postgres -p 5432" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    expose:
      - 5432
    networks:
      - net

  apply_migrations:
    container_name: apply_migrations
    image: romelabs/rome-apps:${HERCULES_TAG:-latest}
    logging: *logging-config
    environment:
      SERVICE_NAME: apply_migrations
      DATABASE_URL: "postgres://hercules:qwerty123@postgres_rome/test_rollup"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net

  proxy:
    container_name: proxy
    image: romelabs/rome-apps:${PROXY_TAG:-latest}
    logging: *logging-config
    hostname: proxy
    environment:
      SERVICE_NAME: proxy
      PROXY_CONFIG: /opt/proxy-config.yml
    volumes:
      - ./cfg/proxy-config.yml:/opt/proxy-config.yml
      - ./keys/proxy-sender.json:/opt/proxy-sender.json
      - ./keys/proxy-sender-2.json:/opt/proxy-sender-2.json
      - ./keys/proxy-sender-3.json:/opt/proxy-sender-3.json
    ports:
      - 9090:9090
    expose:
      - "9090"
    networks:
      - net

  geth:
    container_name: geth
    image: romelabs/rollup-op-geth:${GETH_TAG:-latest}
    logging: *logging-config
    hostname: geth
    environment:
      CHAIN_ID: ${CHAIN_ID}
      GENESIS_ADDRESS: ${GENESIS_ADDRESS}
      GENESIS_BALANCE: 0
      JWT_SECRET: ${JWT_SECRET}
      ROME_GASOMETER_URL: ${GASOMETER_HOST}
      GETH_BASE_DATA_DIR: /opt/geth
    volumes:
      - ./geth:/opt/geth
    ports:
      # - 443:443
      - 8545:8545
      - 8546:8546
      - 8551:8551
    networks:
      - net

  hercules:
    container_name: hercules
    image: romelabs/rome-apps:${HERCULES_TAG:-latest}
    logging: *logging-config
    hostname: hercules
    environment:
      SERVICE_NAME: hercules
      HERCULES_CONFIG: /opt/hercules-config.yml
    volumes:
      - ./cfg/hercules-config.yml:/opt/hercules-config.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:8000
    networks:
      - net

  rhea:
    container_name: rhea
    image: romelabs/rome-apps:${RHEA_TAG:-latest}
    logging: *logging-config
    hostname: rhea
    environment:
      SERVICE_NAME: rhea
      RHEA_CONFIG: /opt/rhea-config.yml
    volumes:
      - ./cfg/rhea-config.yml:/opt/rhea-config.yml
      - ./keys/rhea-sender.json:/opt/rhea-sender.json
      - ./keys/rhea-sender-2.json:/opt/rhea-sender-2.json
      - ./keys/rhea-sender-3.json:/opt/rhea-sender-3.json
    networks:
      - net

  depositui:
    container_name: depositui
    image: romelabs/rome-deposit-ui:${DEPOSIT_UI_TAG:-latest}
    logging: *logging-config
    hostname: depositui
    volumes:
      - ./depositui/env.example:/app/.env
    ports:
      - 3000:3000
    networks:
      - net
    
  romenginx:
    container_name: romenginx
    image: nginx:latest
    logging: *logging-config
    hostname: romenginx
    ports:
      - "2000:2000"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/ssl/ssl.crt:/etc/nginx/ssl/selfsigned.crt:ro
      - /home/ubuntu/ssl/ssl.key:/etc/nginx/ssl/selfsigned.key:ro
    networks:
      - net

networks:
  net:
